# Generated by Django 4.2.20 on 2025-04-06 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureToggle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TblFormDataNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_date', models.DateTimeField()),
                ('cta_url', models.CharField(blank=True, max_length=255)),
                ('cta_source', models.CharField(blank=True, max_length=255)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('refid', models.CharField(blank=True, max_length=100)),
                ('tagid', models.CharField(blank=True, max_length=100)),
                ('subscriber_password', models.CharField(blank=True, max_length=255)),
                ('subscriber_group', models.CharField(blank=True, max_length=100)),
                ('personality_prefix', models.CharField(blank=True, max_length=50)),
                ('shares', models.CharField(default='0', max_length=10)),
                ('credits', models.CharField(default='0', max_length=10)),
                ('decoding_requests', models.CharField(default='0', max_length=10)),
                ('total_submissions', models.CharField(default='0', max_length=10)),
            ],
        ),
    ]
